include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    always_specify_types: true
    always_declare_return_types: true
    avoid_web_libraries_in_flutter: true
    avoid_setters_without_getters: true
    avoid_bool_literals_in_conditional_expressions: true
    cancel_subscriptions: true
    cast_nullable_to_non_nullable: true
    leading_newlines_in_multiline_strings: true
    lines_longer_than_80_chars: false
    literal_only_boolean_expressions: true
    missing_code_block_language_in_doc_comment: true
    missing_whitespace_between_adjacent_strings: true
    no_literal_bool_comparisons: true
    no_logic_in_create_state: true
    no_self_assignments: true
    noop_primitive_operations: true
    parameter_assignments: true
    prefer_const_constructors_in_immutables: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    always_use_package_imports: false
    prefer_relative_imports: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    require_trailing_commas: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    sort_child_properties_last: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_breaks: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    unnecessary_underscores: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_rethrow_when_possible: true
    use_string_in_part_of_directives: true
    use_test_throws_matchers: true
    use_truncating_division: true
    valid_regexps: true
    void_checks: true

 
formatter:
  page_width: 120

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    always_declare_return_types: error
    no_logic_in_create_state: error
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    unrelated_type_equality_checks: warning
    todo: ignore
